name: FoMo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - scipy
  - seaborn>=0.9.0
  - tqdm>=4.32.1
  - hydra-core>=1.3
  - peft
  - transformers
  - datasets
  - accelerate
  - pandas
  - einops 
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch
    - torchvision
    - torchaudio
    - codecarbon
    - lm-eval
    - tensorboard